Repository SUSE/stratos, pull requests merged in 2018-11, with the labels that each got.

#74 Merge upstream
  CHANGELOG.md
  deploy/cloud-foundry/README.md
  docs/status_updates.md
  manifest.yml
  package.json
  src/frontend/app/features/applications/application-delete/application-delete.component.ts
  src/frontend/app/features/applications/application-delete/delete-app-instances/app-delete-instances-routes-list-config.service.ts
  src/frontend/app/features/applications/application-delete/delete-app-instances/delete-app-instances.component.ts
  src/frontend/app/features/applications/application-delete/delete-app-routes/app-delete-routes-list-config.service.ts
  src/frontend/app/features/applications/application-delete/delete-app-routes/delete-app-routes.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-build-packs/cloud-foundry-build-packs.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.scss
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-feature-flags/cloud-foundry-feature-flags.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-organization-spaces.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-users/cloud-foundry-organization-users.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organizations.component.ts
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.ts
  src/frontend/app/shared/components/confirmation-dialog.config.ts
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.html
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.scss
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.spec.ts
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-table/table-cell-select/table-cell-select.component.html
  src/frontend/app/shared/components/list/list-table/table-cell-select/table-cell-select.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/base-cf/base-cf-list-config.ts
  src/frontend/app/shared/components/list/list-types/cf-cell-apps/cf-cell-apps-source.ts
  src/frontend/app/shared/components/list/list-types/cf-cell-health/cf-cell-health-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-cell-health/cf-cell-health-source.ts
  src/frontend/app/shared/components/list/list-types/cf-cells/cf-cells-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/shared/components/metrics-range-selector/metrics-range-selector.component.scss
  src/frontend/app/shared/components/start-end-date/start-end-date.component.ts
  src/frontend/app/shared/data-services/service-action-helper.service.ts
  src/jetstream/plugins/metrics/main.go
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/marketplace/edit-service-instance-e2e.spec.ts
  src/test-e2e/po/confirm-dialog.ts
  src/test-e2e/po/form.po.ts
Labels: ready for review

#76 Fix for unable to connect K8S on CAASP
  src/jetstream/plugins/kubernetes/kube_config.go
Labels: ready for review

#82 Updated log in text
  src/frontend/app/custom/suse-login/suse-login.component.html
Labels: ready for review

#77 Add CAP Docs
  docs/suse/deploy.md
Labels: ready for review

#87 List fix when missing default order, added kube table filtering & default and other improvements
  src/frontend/app/custom/kubernetes/helm-release/helm-release-pods-tab/helm-release-pods-tab.component.ts
  src/frontend/app/custom/kubernetes/list-types/helm-release-pods/helm-release-pods-data-source.ts
  src/frontend/app/custom/kubernetes/list-types/helm-release-pods/helm-release-pods-list-config.service.ts
  src/frontend/app/custom/kubernetes/list-types/helm-release-services/helm-release-services-data-source.ts
  src/frontend/app/custom/kubernetes/list-types/helm-release-services/helm-release-services-list-config.service.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-apps/kubernetes-apps-data-source.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-apps/kubernetes-apps-list-config.service.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-namespace-pods/kubernetes-namespace-pods-data-source.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-namespaces/kubernetes-namespaces-data-source.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-namespaces/kubernetes-namespaces-list-config.service.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-node-pods/kubernetes-node-pods-data-source.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-nodes/kubernetes-nodes-data-source.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-nodes/kubernetes-nodes-list-config.service.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-pods/kubernetes-pods-data-source.ts
  src/frontend/app/custom/kubernetes/list-types/kubernetes-pods/kubernetes-pods-list-config.service.ts
  src/frontend/app/custom/kubernetes/services/helm-release.service.ts
  src/frontend/app/custom/kubernetes/services/kubernetes-endpoint.service.ts
  src/frontend/app/custom/kubernetes/store/kube.types.ts
  src/frontend/app/custom/kubernetes/store/kubernetes.actions.ts
  src/frontend/app/custom/kubernetes/store/kubernetes.effects.ts
  src/frontend/app/custom/kubernetes/tabs/kubernetes-apps-tab/kubernetes-apps-tab.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.ts
  src/frontend/app/shared/components/list/list-table/table.types.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/types/entity.types.ts
Labels: ready for review

#94 Add validation when connecting Kubernetes endpoints
  src/jetstream/auth.go
  src/jetstream/passthrough.go
  src/jetstream/plugins/caasp/main.go
  src/jetstream/plugins/cloudfoundry/main.go
  src/jetstream/plugins/kubernetes/main.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/repository/interfaces/endpoints.go
  src/jetstream/repository/interfaces/portal_proxy.go
Labels: needs attention, ready for review

#98 Merge pull request #3199 from cloudfoundry-incubator/split-travis-e2e
  .travis.yml
  deploy/ci/travis/job-e2e-before_script.sh
  deploy/ci/travis/job-e2e-script.sh
  deploy/ci/travis/run-e2e-tests.sh
  protractor.conf.js
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-deploy-local-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/application/po/deploy-app.po.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/cf-org-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-e2e.spec.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/po/boolean-indicator.po.ts
  src/test-e2e/po/form.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/meta-data-item.po.ts
Labels: ready for review

#97 Fix CPU metric chart when a series is published per CPU core
  src/frontend/app/custom/kubernetes/kubernetes-node/kubernetes-node-metrics/kubernetes-node-metrics.component.ts
  src/frontend/app/custom/kubernetes/pod-metrics/pod-metrics.component.ts
Labels: in review

#96 Show error on kubernetes pages and kubernetes endpoint page.
  src/frontend/app/custom/kubernetes/helm-release/helm-release.component.ts
  src/frontend/app/custom/kubernetes/kubernetes-namespace/kubernetes-namespace.component.ts
  src/frontend/app/custom/kubernetes/kubernetes-node/kubernetes-node.component.ts
  src/frontend/app/custom/kubernetes/kubernetes-tab-base/kubernetes-tab-base.component.ts
  src/frontend/app/custom/kubernetes/kubernetes.routing.ts
  src/frontend/app/custom/kubernetes/pod-metrics/pod-metrics.component.ts
  src/frontend/app/custom/kubernetes/store/kubernetes.effects.ts
  src/frontend/app/features/applications/application/application-base.component.ts
  src/frontend/app/features/applications/applications.routing.ts
  src/frontend/app/features/cloud-foundry/add-organization/add-organization.component.ts
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/add-space/add-space.component.ts
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-base/cloud-foundry-base.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.routing.ts
  src/frontend/app/features/service-catalog/service-catalog.routing.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/features/services/detach-service-instance/detach-service-instance.component.ts
  src/frontend/app/features/services/services.routing.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/list/list-types/detach-apps/detach-apps-list-config.service.ts
  src/frontend/app/shared/components/page-header/page-header-events/page-header-events.component.ts
  src/frontend/app/store/actions/internal-events.actions.ts
  src/frontend/app/store/effects/action-history.effects.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/cloud-foundry.effects.ts
  src/frontend/app/store/effects/endpoint-api-errors.effects.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/effects/metrics.effects.ts
  src/frontend/app/store/reducers/api-request-reducer/request-helpers.ts
  src/frontend/app/store/reducers/internal-events.reducer.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-clear-pagination-type.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/app/store/store.module.ts
  src/frontend/app/store/types/request.types.ts
  src/test-e2e/cloud-foundry/cf-level/cf-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-users-list-e2e.spec.ts
  src/test-e2e/helpers/extend-test-helpers.ts
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
  src/test-e2e/marketplace/edit-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
Labels: ready for review

#100 Fix login tests
  src/frontend/app/custom/suse-login/suse-login.component.html
  src/test-e2e/check/check-login-e2e.spec.ts
  src/test-e2e/login/login.po.ts
  src/test-e2e/login/sso-login.po.ts
Labels: ready for review
