Repository SUSE/stratos, pull requests merged in 2019-08, with the labels that each got.

#187 Final Upstream sync for the 2.5 release
  CHANGELOG.md
  build/tools/changelog.js
  package-lock.json
  package.json
  src/frontend/packages/core/src/features/cloud-foundry/add-quota/create-quota-step/create-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-space-quota/create-space-quota-step/create-space-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-quota/edit-quota-step/edit-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-space-quota/edit-space-quota-step/edit-space-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/quota-definition-form/quota-definition-form.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/packages/store/src/actions/quota-definitions.actions.ts
  src/jetstream/load_plugins.go
  src/jetstream/plugins/demo/main.go
  src/test-e2e/login/sso-login.po.ts
Labels: ready for review

#188 Fix missing icons on Kubernetes
  custom-src/frontend/app/custom/helm/monocular-tab-base/monocular-tab-base.component.ts
  custom-src/frontend/app/custom/helm/monocular/chart-index/chart-index.component.spec.ts
  custom-src/frontend/app/custom/helm/release/helm-release-tab-base/helm-release-tab-base.component.ts
  custom-src/frontend/app/custom/kubernetes/helm-release/helm-release.component.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes-namespace/kubernetes-namespace.component.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes-node/kubernetes-node.component.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes-tab-base/kubernetes-tab-base.component.ts
Labels: ready for review

#173 Tidy up backend code for Kubernetes/Helm
  custom-src/frontend/app/custom/custom.module.ts
  custom-src/frontend/app/custom/helm/monocular/chart-index/chart-index.component.spec.ts
  deploy/ci/tasks/build-images/canary-tag
  src/jetstream/auth_providers.go
  src/jetstream/main.go
  src/jetstream/oauth_requests.go
  src/jetstream/oauth_requests_test.go
  src/jetstream/oidc_requests.go
  src/jetstream/passthrough.go
  src/jetstream/plugins/kubernetes/api_proxy.go
  src/jetstream/plugins/kubernetes/auth/awsiam.go
  src/jetstream/plugins/kubernetes/auth/azure.go
  src/jetstream/plugins/kubernetes/auth/cert.go
  src/jetstream/plugins/kubernetes/auth/cert_tests.go
  src/jetstream/plugins/kubernetes/auth/gke.go
  src/jetstream/plugins/kubernetes/auth/kubeconfig.go
  src/jetstream/plugins/kubernetes/auth/oidc.go
  src/jetstream/plugins/kubernetes/auth/types.go
  src/jetstream/plugins/kubernetes/auth_providers.go
  src/jetstream/plugins/kubernetes/config/kube_config.go
  src/jetstream/plugins/kubernetes/endpoint_config.go
  src/jetstream/plugins/kubernetes/go.mod
  src/jetstream/plugins/kubernetes/go.sum
  src/jetstream/plugins/kubernetes/helm_client.go
  src/jetstream/plugins/kubernetes/helm_versions.go
  src/jetstream/plugins/kubernetes/install_release.go
  src/jetstream/plugins/kubernetes/kube_config.go
  src/jetstream/plugins/kubernetes/kube_dashboard.go
  src/jetstream/plugins/kubernetes/list_releases.go
  src/jetstream/plugins/kubernetes/main.go
  src/jetstream/plugins/monocular/20190307115300_ChartStore.go
  src/jetstream/plugins/monocular/chartsvc/datastore.go
  src/jetstream/plugins/monocular/chartsvc/handler.go
  src/jetstream/plugins/monocular/chartsvc/mongodb.go
  src/jetstream/plugins/monocular/endpoint.go
  src/jetstream/plugins/monocular/main.go
  src/jetstream/plugins/monocular/repository.go
  src/jetstream/plugins/monocular/sql_datastore.go
  src/jetstream/plugins/monocular/sync.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/jetstream/repository/interfaces/structs.go
Labels: needs attention, ready for review

#192 Merge upstream
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/containers/nginx/conf/nginx.dev.conf
  deploy/containers/nginx/conf/nginx.k8s.conf
  deploy/kubernetes/build.sh
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
  deploy/kubernetes/imagelist-gen.sh
  deploy/stratos-ui-release/jobs/frontend/templates/nginx.conf.erb
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/customizations.types.ts
  src/frontend/packages/core/src/core/extension/extension-types.ts
  src/frontend/packages/core/src/features/about/diagnostics-page/diagnostics-page.component.html
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-base-step/create-endpoint-base-step.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoint-helpers.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/reducers/auth.reducer.ts
  src/frontend/packages/store/src/types/auth.types.ts
  src/jetstream/auth_test.go
  src/jetstream/default.config.properties
  src/jetstream/info.go
  src/jetstream/main.go
  src/jetstream/repository/interfaces/structs.go
Labels: ready for review

#190 Tech preview for helm feature
  custom-src/frontend/app/custom/custom.module.ts
  custom-src/frontend/app/custom/helm/helm.store.module.ts
  src/jetstream/plugins/kubernetes/main.go
  src/jetstream/plugins/monocular/main.go
  src/test-e2e/cloud-foundry/cloud-foundry-list-cf-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/po/side-nav.po.ts
Labels: in review, ready for review

#193 Allow DB directory to be specified for SQLite
  src/jetstream/datastore/datastore.go
Labels: ready for review

#174 Helm ui tweaks
  custom-src/frontend/app/custom/custom.module.ts
  custom-src/frontend/app/custom/helm/create-release/create-release.component.html
  custom-src/frontend/app/custom/helm/create-release/create-release.component.scss
  custom-src/frontend/app/custom/helm/create-release/create-release.component.spec.ts
  custom-src/frontend/app/custom/helm/create-release/create-release.component.ts
  custom-src/frontend/app/custom/helm/monocular/chart-details/chart-details-info/chart-details-info.component.spec.ts
  custom-src/frontend/app/custom/helm/monocular/chart-details/chart-details-readme/chart-details-readme.component.ts
  custom-src/frontend/app/custom/helm/monocular/chart-details/chart-details.component.html
  custom-src/frontend/app/custom/helm/monocular/chart-index/chart-index.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
Labels: in review, ready for review

#194 Custom welcome message on endpoints page (admin)
  custom-src/frontend/app/custom/custom.module.ts
  custom-src/frontend/app/custom/suse-welcome/suse-welcome.component.html
  custom-src/frontend/app/custom/suse-welcome/suse-welcome.component.scss
  custom-src/frontend/app/custom/suse-welcome/suse-welcome.component.ts
  src/frontend/packages/core/src/app.component.spec.ts
  src/frontend/packages/core/src/core/customizations.types.ts
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.html
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoints.module.ts
  src/frontend/packages/core/src/shared/components/cf-endpoints-missing/cf-endpoints-missing.component.spec.ts
  src/frontend/packages/core/src/shared/components/cf-endpoints-missing/cf-endpoints-missing.component.ts
  src/frontend/packages/core/src/shared/components/endpoints-missing/endpoints-missing.component.html
  src/frontend/packages/core/src/shared/components/endpoints-missing/endpoints-missing.component.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-unregister-e2e.spec.ts
  src/test-e2e/endpoints/endpoints.po.ts
Labels: ready for review
