Repository SUSE/stratos, pull requests merged in 2020-02, with the labels that each got.

#303 Add workloads icon
  custom-src/frontend/app/custom/custom-routing.module.ts
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.eot
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.svg
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.ttf
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.woff
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.woff2
Labels: ready for review

#297 V3: Fix user profile (merge from upstream)
  deploy/kubernetes/console/templates/deployment.yaml
  src/jetstream/plugins/userinfo/local_user.go
  src/jetstream/plugins/userinfo/main.go
  src/jetstream/plugins/userinfo/types.go
  src/jetstream/plugins/userinfo/uaa_user.go
Labels: ready for review

#301 Sidepanel UI fixes
  custom-src/frontend/app/custom/kubernetes/kubernetes-resource-viewer/kubernetes-resource-viewer.component.html
  custom-src/frontend/app/custom/kubernetes/kubernetes-resource-viewer/kubernetes-resource-viewer.component.scss
  custom-src/frontend/app/custom/kubernetes/kubernetes-resource-viewer/kubernetes-resource-viewer.component.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-pods/kubernetes-pods-list-config.service.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-services/kubernetes-service-list-config.service.ts
  custom-src/frontend/sass/custom/suse.scss
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.scss
  src/frontend/packages/core/src/shared/components/sidepanel-preview/sidepanel-preview.component.scss
  src/frontend/packages/core/src/shared/components/sidepanel-preview/sidepanel-preview.component.theme.scss
Labels: ready for review

#286 Kubernetes Dashboard fixes (V2 port)
  CHANGELOG.md
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubedash-configuration/kubedash-configuration.component.html
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubedash-configuration/kubedash-configuration.component.scss
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubedash-configuration/kubedash-configuration.component.spec.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubedash-configuration/kubedash-configuration.component.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubernetes-dashboard.component.html
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubernetes-dashboard.component.scss
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubernetes-dashboard.component.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes.module.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes.routing.ts
  custom-src/frontend/app/custom/kubernetes/services/kubernetes-endpoint.service.ts
  custom-src/frontend/app/custom/kubernetes/store/kubernetes.effects.ts
  custom-src/frontend/app/custom/kubernetes/tabs/kubernetes-summary-tab/kubernetes-summary.component.html
  custom-src/frontend/app/custom/kubernetes/tabs/kubernetes-summary-tab/kubernetes-summary.component.scss
  custom-src/frontend/app/custom/kubernetes/tabs/kubernetes-summary-tab/kubernetes-summary.component.ts
  custom-src/stratos.yaml
  deploy/kubernetes/console/values.yaml
  src/frontend/packages/core/src/core/theme.service.ts
  src/frontend/packages/core/src/shared/components/card-progress-overlay/card-progress-overlay.component.html
  src/frontend/packages/core/src/shared/components/card-progress-overlay/card-progress-overlay.component.scss
  src/frontend/packages/core/src/shared/components/card-progress-overlay/card-progress-overlay.component.spec.ts
  src/frontend/packages/core/src/shared/components/card-progress-overlay/card-progress-overlay.component.theme.scss
  src/frontend/packages/core/src/shared/components/card-progress-overlay/card-progress-overlay.component.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/jetstream/datastore/20200117152200_SesssionData.go
  src/jetstream/main.go
  src/jetstream/middleware.go
  src/jetstream/passthrough.go
  src/jetstream/plugins/kubernetes/dashboard/common.go
  src/jetstream/plugins/kubernetes/dashboard/configure.go
  src/jetstream/plugins/kubernetes/dashboard/login.go
  src/jetstream/plugins/kubernetes/dashboard/proxy.go
  src/jetstream/plugins/kubernetes/dashboard/status.go
  src/jetstream/plugins/kubernetes/dashboard/yaml.go
  src/jetstream/plugins/kubernetes/kube_dashboard.go
  src/jetstream/plugins/kubernetes/main.go
  src/jetstream/portal_proxy.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/jetstream/repository/interfaces/sessiondata.go
  src/jetstream/repository/sessiondata/cleanup.go
  src/jetstream/repository/sessiondata/psql_sessiondata.go
  src/jetstream/session.go
Labels: ready for review

#302 Fixes/Improvements following helm walkthrough #2
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubedash-configuration/kubedash-configuration.component.html
  custom-src/frontend/app/custom/kubernetes/kubernetes-dashboard/kubedash-configuration/kubedash-configuration.component.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-namespace-pods/kubernetes-namespace-pods-list-config.service.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-namespaces/kubernetes-namespaces-list-config.service.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-node-pods/kubernetes-node-pods-list-config.service.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-nodes/kubernetes-node-capacity/kubernetes-node-capacity.component.html
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-nodes/kubernetes-nodes-list-config.service.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-pods/kubernetes-pod-status/kubernetes-pod-status.component.html
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-pods/kubernetes-pod-status/kubernetes-pod-status.component.spec.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-pods/kubernetes-pod-status/kubernetes-pod-status.component.ts
  custom-src/frontend/app/custom/kubernetes/list-types/kubernetes-pods/kubernetes-pods-list-config.service.ts
  custom-src/frontend/app/custom/kubernetes/services/kubernetes-endpoint.service.ts
  custom-src/frontend/app/custom/kubernetes/services/kubernetes-expanded-state.ts
  custom-src/frontend/app/custom/kubernetes/tabs/kubernetes-summary-tab/kubernetes-summary.component.html
  custom-src/frontend/app/custom/kubernetes/tabs/kubernetes-summary-tab/kubernetes-summary.component.scss
  custom-src/frontend/app/custom/kubernetes/workloads/list-types/helm-release-card/helm-release-card.component.html
  custom-src/frontend/app/custom/kubernetes/workloads/list-types/helm-release-card/helm-release-card.component.scss
  custom-src/frontend/app/custom/kubernetes/workloads/list-types/helm-release-card/helm-release-card.component.spec.ts
  custom-src/frontend/app/custom/kubernetes/workloads/list-types/helm-release-card/helm-release-card.component.ts
  custom-src/frontend/app/custom/kubernetes/workloads/list-types/helm-release-pods-list-config.service.ts
  custom-src/frontend/app/custom/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  custom-src/frontend/app/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.html
  custom-src/frontend/app/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.scss
  custom-src/frontend/app/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/service-icon/service-icon.component.html
  src/frontend/packages/core/src/shared/components/card-progress-overlay/card-progress-overlay.component.scss
  src/frontend/packages/core/src/shared/components/entity-summary-title/entity-summary-title.component.html
  src/frontend/packages/core/src/shared/components/entity-summary-title/entity-summary-title.component.scss
  src/frontend/packages/core/src/shared/components/entity-summary-title/entity-summary-title.component.ts
  src/frontend/packages/core/src/shared/components/ring-chart/ring-chart.component.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/forced-action-type.helpers.ts
Labels: ready for review

#313 Add loading indicator for Workload resource stats
  custom-src/frontend/app/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.html
  custom-src/frontend/app/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.ts
Labels: ready for review

#321 V3 pipeline updates
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-helm-chart-pr.yml
Labels: ready for review

#316 Update SLE base images
  deploy/stratos-base-images/Dockerfile.stratos-bk-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-bk-init-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-go-build-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-mariadb-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-nginx-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-ruby-build-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-ui-build-base.tmpl
  deploy/stratos-base-images/build-base-images.sh
Labels: ready for review

#317 Upstream helm chart fixes
  deploy/cap/bower.json
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-nightly-releases.yml
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/ci/tasks/dev-releases/nightly-release-name
  deploy/ci/tasks/dev-releases/nightly-tag
  deploy/kubernetes/build.sh
  deploy/kubernetes/console/Chart.yaml
  deploy/kubernetes/console/README.md
  deploy/kubernetes/console/icon.png
  deploy/kubernetes/console/templates/config-init.yaml
  deploy/kubernetes/console/templates/database.yaml
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/templates/service.yaml
  deploy/kubernetes/console/tests/custom_annotations_test.yaml
  deploy/kubernetes/console/tests/service_test.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#318 Bug fix: Broken user profile when using local admin user
  src/jetstream/plugins/userinfo/uaa_user.go
Labels: bug, ready for review

#322 CI Pipeline fix
  deploy/ci/suse-console-dev-releases.yml
Labels: ready for review

#236 Helm: Add customization of helm chart for SUSE
  custom-src/deploy/kubernetes/customize-helm.sh
  custom-src/deploy/kubernetes/icon.png
Labels: do not merge

#323 Fix CI image build pipeline
  deploy/ci/suse-console-dev-releases.yml
Labels: ready for review

#324 CI Pipelines: Add missing chartsync image
  deploy/ci/suse-console-dev-releases.yml
  deploy/kubernetes/console/templates/chartsync.yaml
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#326 Fix favourites update bug on mysql
  src/jetstream/plugins/userfavorites/userfavoritesstore/favorites-store-db.go
Labels: ready for review

#327 Add docs for external db
  deploy/kubernetes/console/README.md
Labels: ready for review

#325 Add support for TLS with MySQL
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
  src/jetstream/datastore/20190522121200_LocalUsers.go
  src/jetstream/datastore/20190930092500_LocalUsersTriggerFix.go
  src/jetstream/datastore/datastore.go
  src/jetstream/go.mod
  src/jetstream/go.sum
  src/jetstream/main_test.go
Labels: ready for review

#328 Helm: Fixes for upgrade and SUSE patches
  custom-src/deploy/kubernetes/customize-helm.sh
  deploy/containers/monocular/fdb-doclayer/fdb-doc-layer-networkpolicy.yaml
  deploy/containers/monocular/fdb-server/fdbserver-networkpolicy.yaml
  deploy/db/mariadb-entrypoint.sh
  deploy/kubernetes/build.sh
  deploy/kubernetes/console/templates/chartsync.yaml
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/templates/local-helm/fdbdoclayer/templates/fdb-doc-layer-deployment.yaml
  deploy/kubernetes/console/templates/local-helm/fdbdoclayer/templates/fdb-doc-layer-service.yaml
  deploy/kubernetes/console/templates/local-helm/fdbdoclayer/templates/fdbserver-deployment.yaml
  deploy/kubernetes/console/templates/local-helm/fdbdoclayer/templates/fdbserver-service.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#329 Hide required markers on login page
  custom-src/frontend/app/custom/suse-login/suse-login.component.html
Labels: ready for review

#332 Fix helm chart bug
  deploy/kubernetes/console/templates/deployment.yaml
Labels: ready for review

#331 Fdb doclayer combine
  deploy/containers/monocular/fdb-doclayer/fdbdoc.bash
  deploy/containers/monocular/fdb-server/fdb.bash
  deploy/kubernetes/console/templates/local-helm/fdbdoclayer/templates/deployment.yaml
  deploy/kubernetes/console/templates/local-helm/fdbdoclayer/templates/fdb-doc-layer-service.yaml
  deploy/kubernetes/console/templates/service.yaml
  deploy/kubernetes/temp/fdb-doc-layer-deployment.yaml
  deploy/kubernetes/temp/fdbserver-deployment.yaml
  deploy/kubernetes/temp/fdbserver-service.yaml
Labels: ready for review

#339 Fix helm chart patching for SUSE
  custom-src/deploy/kubernetes/customize-helm.sh
  deploy/kubernetes/build.sh
Labels: ready for review

#340 Helm chart tweaks to readme
  custom-src/deploy/kubernetes/customize-helm.sh
  deploy/kubernetes/console/README.md
  deploy/kubernetes/console/requirements.lock
Labels: ready for review

#305 Metrics fixes
  custom-src/frontend/app/custom/kubernetes/kubernetes-metrics.helpers.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes-node/kubernetes-node-metrics/kubernetes-node-metrics.component.ts
  custom-src/frontend/app/custom/kubernetes/kubernetes-node/kubernetes-node-metrics/kubernetes-node-simple-metric/kubernetes-node-simple-metric.component.html
  custom-src/frontend/app/custom/kubernetes/kubernetes-node/kubernetes-node-metrics/kubernetes-node-simple-metric/kubernetes-node-simple-metric.component.ts
  custom-src/frontend/app/custom/kubernetes/pod-metrics/pod-metrics.component.ts
  custom-src/frontend/app/custom/kubernetes/services/kubernetes-node.service.ts
  src/frontend/packages/core/src/shared/components/metrics-chart/metrics-chart.component.html
  src/frontend/packages/core/src/shared/components/metrics-chart/metrics-chart.component.scss
  src/frontend/packages/core/src/shared/components/metrics-chart/metrics-chart.component.ts
  src/frontend/packages/core/src/shared/components/metrics-chart/metrics.component.helpers.ts
  src/frontend/packages/core/src/shared/components/metrics-chart/metrics.component.manager.ts
  src/frontend/packages/store/src/types/base-metric.types.ts
Labels: ready for review

#336 Make it easier to use chartsync tool in development
  build/chartsync-build.sh
  package.json
  src/jetstream/default.config.properties
  src/jetstream/main.go
  src/jetstream/plugins/monocular/go.sum
  src/jetstream/plugins/monocular/main.go
  src/jetstream/repository/interfaces/plugin.go
Labels: ready for review

#337 Minor Helm UI Tweaks
  custom-src/frontend/app/custom/helm/create-release/create-release.component.ts
  custom-src/frontend/app/custom/helm/list-types/monocular-repository-list-config.service.ts
  src/jetstream/plugins/monocular/main.go
  src/jetstream/plugins/monocular/sync.go
Labels: ready for review

#344 Fix Kubernetes connect issues
  custom-src/frontend/app/custom/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.ts
  src/jetstream/passthrough.go
  src/jetstream/plugins/kubernetes/auth/token.go
  src/jetstream/plugins/kubernetes/main.go
Labels: ready for review

#342 Changelog for 3.0.0
  CHANGELOG.md
Labels: ready for review
