Repository SUSE/stratos, pull requests merged in 2020-09, with the labels that each got.

#462 Fix issue where kube dependency vbom.ml/util is no longer available
  src/jetstream/go.sum
  src/jetstream/plugins/kubernetes/go.mod
Labels: ready for review

#443 Add a 'live reload' button to workload views
  src/frontend/packages/suse-extensions/src/custom/kubernetes/kubernetes.testing.module.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/helm-release-tab-base/helm-release-socket-service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/helm-release-tab-base/helm-release-tab-base.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-helpers.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-pods/helm-release-pods-tab.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-pods/helm-release-pods-tab.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-pods/helm-release-pods-tab.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-resource-graph/helm-release-resource-graph.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-resource-graph/helm-release-resource-graph.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-services/helm-release-services-tab.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-services/helm-release-services-tab.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-services/helm-release-services-tab.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/workload-live-reload/workload-live-reload.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/workload-live-reload/workload-live-reload.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/workload-live-reload/workload-live-reload.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/workload-live-reload/workload-live-reload.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads.module.ts
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/plugins/kubernetes/get_release.go
Labels: comments-addressed, ready for review

#461 Update Kube Resource Icons
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/icon-helper.ts
Labels: ready for review

#464 Indicate if the Helm chart has a schema
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-info/chart-details-info.component.html
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-info/chart-details-info.component.scss
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-info/chart-details-info.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-usage/chart-details-usage.component.html
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-versions/chart-details-versions.component.scss
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/shared/models/chart-version.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/shared/services/charts.service.ts
  src/jetstream/plugins/monocular/chartsvc/foundationdb/handler.go
Labels: ready for review

#465 Enable linting for suse-extensions package
  angular.json
  package-lock.json
  package.json
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-item/chart-item.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/list-filters/list-filters.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/list-item/list-item.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/loader/loader.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/panel/panel.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.effects.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/kube-config-registration/kube-config-selection/kube-config-selection.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/kube-config-registration/kube-config-selection/kube-config-table-name/kube-config-table-name.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/kube-config-registration/kube-config-selection/kube-config-table-name/kube-config-table-name.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/kube-config-registration/kube-config.types.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/kubernetes-resource-viewer/kubernetes-resource-viewer.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/kubernetes.setup.module.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/analysis-reports-list-source.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/kubernetes-pods/kubernetes-pod-containers/kubernetes-pod-containers.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes.analysis.service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/services/route.helper.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/store/action-builders/kube.action-builders.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/store/analysis.actions.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/store/analysis.effects.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/helm-release-tab-base/helm-release-socket-service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/icon-helper.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-analysis-tab/helm-release-analysis-tab.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-resource-graph/helm-release-resource-graph.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/store/workloads-entity-factory.ts
  src/frontend/packages/suse-extensions/src/custom/suse-welcome/suse-welcome.component.ts
  src/frontend/packages/suse-extensions/tslint.json
  tslint.json
Labels: ready for review

#434 Filter endpoints by type
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-endpoints/cf-endpoints-list-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/base-endpoints-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoints-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list.component.html
  src/frontend/packages/core/src/shared/components/list/list.component.types.ts
  src/frontend/packages/store/src/actions/pagination.actions.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-clear-pagination-type.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-create-pagination.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-reset-pagination.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/packages/suse-extensions/src/custom/helm/list-types/monocular-repository-list-config.service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/kubernetes-endpoints/kubernetes-endpoints-data-source.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/kubernetes-endpoints/kubernetes-endpoints-list-config.service.ts
Labels: comments-addressed, ready for review

#458 Add support for Helm Upgrade and history
  src/frontend/packages/core/sass/mat-desktop.scss
  src/frontend/packages/core/src/shared/components/list/list.component.html
  src/frontend/packages/core/src/shared/components/list/list.component.types.ts
  src/frontend/packages/core/src/shared/components/stepper/step/step.component.ts
  src/frontend/packages/core/src/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/packages/suse-extensions/sass/_all-theme.scss
  src/frontend/packages/suse-extensions/src/custom/helm/helm-entity-catalog.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm-entity-factory.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm-entity-generator.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.action-builders.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.actions.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.effects.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.types.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/helm-release-tab-base/helm-release-tab-base.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-history-tab/helm-release-history-tab.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-history-tab/helm-release-history-tab.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-history-tab/helm-release-history-tab.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-history-tab/helm-release-history-tab.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.theme.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/store/workload-action-builders.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/store/workloads-entity-factory.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/store/workloads-entity-generator.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/store/workloads.actions.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/store/workloads.effects.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/release-version-data-source.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/release-version-list-config.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workload.types.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads-entity-catalog.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads.module.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads.routing.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads.testing.module.ts
  src/jetstream/plugins/kubernetes/install_release.go
  src/jetstream/plugins/kubernetes/main.go
Labels: comments-addressed, ready for review

#463 Helm: Allow users to view and use repositories from Helm Hub
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-base-step/create-endpoint-base-step.component.ts
  src/frontend/packages/core/src/shared/components/cards/card-number-metric/card-number-metric.component.scss
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.scss
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/core/src/shared/components/tile-selector/tile-selector.component.ts
  src/frontend/packages/core/xsrf.module.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.types.ts
  src/frontend/packages/suse-extensions/src/custom/helm/chart-view/monocular.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/create-release/create-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm-entity-factory.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm-entity-generator.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm-hub-registration/helm-hub-registration.component.html
  src/frontend/packages/suse-extensions/src/custom/helm/helm-hub-registration/helm-hub-registration.component.scss
  src/frontend/packages/suse-extensions/src/custom/helm/helm-hub-registration/helm-hub-registration.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm-hub-registration/helm-hub-registration.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm.module.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm.routing.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm.setup.module.ts
  src/frontend/packages/suse-extensions/src/custom/helm/list-types/monocular-charts-data-source.ts
  src/frontend/packages/suse-extensions/src/custom/helm/list-types/monocular-charts-list-config.service.ts
  src/frontend/packages/suse-extensions/src/custom/helm/list-types/monocular-repository-list-config.service.ts
  src/frontend/packages/suse-extensions/src/custom/helm/list-types/monocular-repository-list-source.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular-tab-base/monocular-tab-base.component.html
  src/frontend/packages/suse-extensions/src/custom/helm/monocular-tab-base/monocular-tab-base.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular.interceptor.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-usage/chart-details-usage.component.html
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-usage/chart-details-usage.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-versions/chart-details-versions.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-item/chart-item.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-item/chart-item.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/monocular.module.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/shared/models/chart.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/shared/services/charts.service.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/shared/services/repos.service.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/stratos-monocular-providers.helpers.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/stratos-monocular.helper.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.action-builders.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.actions.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.effects.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.types.ts
  src/frontend/packages/suse-extensions/src/custom/helm/tabs/repository-tab/repository-tab.component.html
  src/frontend/packages/suse-extensions/src/custom/helm/tabs/repository-tab/repository-tab.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/helm/tabs/repository-tab/repository-tab.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/store/workloads.effects.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/release-version-data-source.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/release-version-list-config.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads.routing.ts
  src/jetstream/datastore/20200902162200_HelmSubtype.go
  src/jetstream/passthrough.go
  src/jetstream/plugins/kubernetes/install_release.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/plugins/monocular/main.go
Labels: comments-addressed, ready for review

#472 Fix valid state of helm install & fixes missing from helm hub pr
  src/frontend/packages/suse-extensions/src/custom/helm/create-release/create-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.effects.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-history-tab/helm-release-history-tab.component.ts
Labels: ready for review

#474 Workloads List: Show chart version instead of release version
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/list-types/helm-release-card/helm-release-card.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/list-types/helm-releases-list-config.service.ts
Labels: ready for review

#476 Login Screen: Hide form during initial verify
  src/frontend/packages/core/src/features/login/login-page/login-page.component.ts
  src/frontend/packages/suse-extensions/src/custom/suse-login/suse-login.component.html
  src/frontend/packages/suse-extensions/src/custom/suse-login/suse-login.component.scss
Labels: ready for review

#477 Fix SSO Error message & helm chart list on helm hub register/unregister
  src/frontend/packages/core/src/features/login/login-page/login-page.component.theme.scss
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.effects.ts
  src/frontend/packages/suse-extensions/src/custom/suse-login/suse-login.component.scss
Labels: ready for review

#469 Helm: Improve experience for editing chart values
  angular.json
  package.json
  src/frontend/packages/suse-extensions/sass/_all-theme.scss
  src/frontend/packages/suse-extensions/src/custom/helm/create-release/create-release.component.scss
  src/frontend/packages/suse-extensions/src/custom/helm/create-release/create-release.module.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm.module.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm.routing.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-usage/chart-details-usage.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.theme.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/diffvalues.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/json-schema-generator.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads.module.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads.routing.ts
Labels: ready for review

#479 Fix db lock issue
  src/jetstream/plugins/monocular/main.go
  src/jetstream/plugins/monocular/store/chart_store_db.go
  src/jetstream/plugins/monocular/sync_worker.go
Labels: ready for review

#482 Helm Values Editor: Bug fixes
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/diffvalues.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/merge.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.ts
Labels: ready for review

#483 Update CI pipelines
  deploy/ci/console-dev-releases.yml
  deploy/ci/suse-console-dev-releases.yml
Labels: ready for review

#485 Update package-lock
  package-lock.json
Labels: ready for review

#486 Ensure wide helm chart logos are not cropped in chart list
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-item/chart-item.component.scss
Labels: ready for review

#487 Helm Chart Store: Truncate fields to fit db width
  src/jetstream/plugins/monocular/chart_svc.go
  src/jetstream/plugins/monocular/store/chart_store_db.go
Labels: ready for review

#489 Ensure service name is correct in helm chart NOTES.txt
  deploy/kubernetes/console/templates/NOTES.txt
Labels: ready for review

#488 Ensure the api key secret db field is long enough
  src/jetstream/datastore/20200814140918_ApiKeys.go
Labels: ready for review

#491 Fix created date issue on helm chart re-sync
  src/jetstream/plugins/monocular/store/chart_store_db.go
Labels: bug, ready for review

#490 Add chart link in charts table, refresh endpoints status on sync
  src/frontend/packages/suse-extensions/src/custom/helm/chart-view/monocular.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/helm-entity-generator.ts
  src/frontend/packages/suse-extensions/src/custom/helm/list-types/monocular-charts-list-config.service.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-versions/chart-details-versions.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-versions/chart-details-versions.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-item/chart-item.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/shared/services/charts.service.ts
  src/frontend/packages/suse-extensions/src/custom/helm/tabs/catalog-tab/catalog-tab.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.ts
Labels: ready for review

#492 Update mariadb helper script
  build/tools/mysqldb-dev.sh
  src/jetstream/config.dev
  src/jetstream/config.example
Labels: ready for review

#493 Fix issue where charts list errors if only helm hub registered
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.effects.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.scss
  src/jetstream/go.sum
Labels: ready for review

#500 Helm Install: fix issue where invalid yaml throws an error
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.ts
Labels: bug, in review

#495 Fix duplicated repo name ids
  src/frontend/packages/suse-extensions/src/custom/helm/helm-entity-factory.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details.component.html
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.effects.ts
Labels: ready for review

#501 Fix issue where kube terminal adds helm hub as a repository
  src/jetstream/plugins/kubernetes/terminal/helpers.go
Labels: bug, in review

#503 Fix issue with Schemas on Helm Hub
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/chart-details/chart-details-info/chart-details-info.component.ts
  src/frontend/packages/suse-extensions/src/custom/helm/monocular/shared/services/charts.service.ts
  src/frontend/packages/suse-extensions/src/custom/helm/store/helm.types.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/create-release/create-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.spec.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/upgrade-release/upgrade-release.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workload.utils.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/workloads.module.ts
  src/jetstream/plugins/monocular/chart.go
  src/jetstream/plugins/monocular/chart_svc.go
  src/jetstream/plugins/monocular/main.go
Labels: bug

#504 Merge upstream
  deploy/ci/tasks/dev-releases/check-gh-release.yml
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
  deploy/ci/tasks/dev-releases/update-gh-release.yml
  deploy/ci/tasks/dev-releases/vars-helper.sh
  deploy/kubernetes/console/templates/deployment.yaml
  src/jetstream/config.dev
Labels: ready for review

#506 Kube Terminal: Appears to hang if it takes a while to start up
  src/jetstream/plugins/kubernetes/terminal/helpers.go
  src/jetstream/plugins/kubernetes/terminal/start.go
Labels: bug, ready for review

#507 Release pipeline tag fix
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-helm-chart-pr.yml
  deploy/ci/console-make-release.yml
  deploy/ci/suse-console-dev-releases.yml
Labels: ready for review

#510 Fix caasp labels
  src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/kubernetes-nodes/kubernetes-node-link/kubernetes-node-link.component.html
  src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/kubernetes-nodes/kubernetes-node-link/kubernetes-node-link.component.scss
  src/frontend/packages/suse-extensions/src/custom/kubernetes/list-types/kubernetes-nodes/kubernetes-node-summary/kubernetes-node-summary-card/kubernetes-node-summary-card.component.ts
  src/frontend/packages/suse-extensions/src/custom/kubernetes/services/kubernetes-endpoint.service.ts
Labels: bug, ready for review

#511 Helm: Only use diff values from form
  src/frontend/packages/suse-extensions/src/custom/kubernetes/workloads/chart-values-editor/chart-values-editor.component.ts
Labels: ready for review

#508 Move suse specific login theme out of default login theme
  src/frontend/packages/core/src/features/login/login-page/login-page.component.theme.scss
  src/frontend/packages/suse-extensions/sass/_all-theme.scss
  src/frontend/packages/suse-extensions/src/custom/suse-login/suse-login.component.theme.scss
Labels: ready for review
