Repository SUSE/stratos, pull requests merged in 2020-10, with the labels that each got.

#520 Don't run doc actions on forks
  .github/workflows/documentation-versioning.yml
  .github/workflows/documentation.yml
  website/internal-versions.json
Labels: ready for review

#515 Fix: Workload shows upgrade when chart has been removed
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
Labels: bug, ready for review

#517 Fix: YAML editor does not load when installing Stratos Helm Chart
  src/frontend/packages/kubernetes/src/kubernetes/workloads/chart-values-editor/merge.ts
Labels: bug, ready for review

#518 First round of improvements to Helm Chart schema
  deploy/kubernetes/console/values.schema.json
Labels: ready for review

#519 Helm chart and CI changes for upstreaming
  deploy/ci/console-dev-releases.yml
  deploy/kubernetes/build.sh
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/custom/__stratos.tpl
  deploy/kubernetes/custom/custom-build.sh
  deploy/kubernetes/custom/customize-helm.sh
Labels: ready for review

#513 Fix upgrade not showing when an RC is deployed
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-helper.service.spec.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
Labels: bug, comments-addressed, ready for review

#521 Move analysis assets from suse-theme to kubernetes package
  src/frontend/packages/kubernetes/assets/custom/analysis/kubescore.md
  src/frontend/packages/kubernetes/assets/custom/analysis/kubescore.png
  src/frontend/packages/kubernetes/assets/custom/analysis/popeye.md
  src/frontend/packages/kubernetes/assets/custom/analysis/popeye.png
  src/frontend/packages/kubernetes/assets/custom/analysis/sonobuoy.md
  src/frontend/packages/kubernetes/assets/custom/analysis/sonobuoy.png
  src/frontend/packages/kubernetes/assets/custom/analysis/sonobuoy.svg
  src/frontend/packages/kubernetes/src/kubernetes/services/kubernetes.analysis.service.ts
Labels: ready for review

#525 Merge upstream
  CHANGELOG.md
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
  src/frontend/packages/kubernetes/src/helm/helm-entity-generator.ts
  src/frontend/packages/kubernetes/src/helm/helm-hub-registration/helm-hub-registration.component.html
  src/frontend/packages/kubernetes/src/helm/helm-hub-registration/helm-hub-registration.component.ts
  src/frontend/packages/kubernetes/src/helm/monocular/chart-details/chart-details.component.ts
  src/frontend/packages/kubernetes/src/helm/monocular/shared/services/charts.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  src/jetstream/config.example
  src/jetstream/plugins/monocular/artifacthub.go
  src/jetstream/plugins/monocular/cache.go
  src/jetstream/plugins/monocular/chart_svc.go
  src/jetstream/plugins/monocular/main.go
  src/jetstream/plugins/monocular/sync_worker.go
Labels: ready for review

#526 Update product version to 2.1.0
  stratos.yaml
Labels: ready for review

#529 420 upstream merge
  .travis.yml
  build/bk-build.sh
  deploy/ci/travis/e2e-build-script.sh
  deploy/ci/travis/install-go.sh
  deploy/ci/travis/run-backend-tests.sh
  deploy/common-build.sh
  deploy/containers/kube-terminal/kubeconsole.bashrc
  deploy/containers/nginx/conf/nginx.dev.conf
  deploy/containers/nginx/conf/nginx.k8s.conf
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/stratos-ui-release/jobs/frontend/templates/nginx.conf.erb
  src/frontend/packages/cloud-foundry/src/shared/q-param.ts
  src/frontend/packages/kubernetes/sass/_all-theme.scss
  src/frontend/packages/kubernetes/src/helm/helm-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.html
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.spec.ts
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.theme.scss
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes.setup.module.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/upgrade-release/upgrade-release.component.ts
  src/jetstream/config.example
  src/jetstream/go.mod
  src/jetstream/go.sum
  src/jetstream/plugins/analysis/container/go.mod
  src/jetstream/plugins/analysis/container/go.sum
  src/jetstream/plugins/analysis/container/main.go
  src/jetstream/plugins/kubernetes/auth/token.go
  src/jetstream/plugins/monocular/20201007113503_RemoveHelmHub.go
  src/jetstream/plugins/monocular/go.sum
  src/jetstream/plugins/monocular/main.go
Labels: ready for review

#531 Upstream merge
  build/bk-build.sh
Labels: ready for review

#533 Merge upstream
  .travis.yml
  CHANGELOG.md
  deploy/kubernetes/console/README.md
  package-lock.json
  package.json
  src/jetstream/main.go
Labels: ready for review
